# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainPage(object):
    def setupUi(self, MainPage):
        MainPage.setObjectName("MainPage")
        MainPage.resize(292, 300)
        self.lineEdit = QtWidgets.QLineEdit(MainPage)
        self.lineEdit.setGeometry(QtCore.QRect(30, 20, 101, 31))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.pbt1 = QtWidgets.QPushButton(MainPage)
        self.pbt1.setGeometry(QtCore.QRect(40, 80, 41, 31))
        self.pbt1.setObjectName("pbt1")
        self.pbt2 = QtWidgets.QPushButton(MainPage)
        self.pbt2.setGeometry(QtCore.QRect(90, 80, 41, 31))
        self.pbt2.setObjectName("pbt2")
        self.pbt3 = QtWidgets.QPushButton(MainPage)
        self.pbt3.setGeometry(QtCore.QRect(150, 80, 41, 31))
        self.pbt3.setObjectName("pbt3")
        self.pbt4 = QtWidgets.QPushButton(MainPage)
        self.pbt4.setGeometry(QtCore.QRect(40, 120, 41, 31))
        self.pbt4.setObjectName("pbt4")
        self.pbt5 = QtWidgets.QPushButton(MainPage)
        self.pbt5.setGeometry(QtCore.QRect(90, 120, 41, 31))
        self.pbt5.setObjectName("pbt5")
        self.pbt6 = QtWidgets.QPushButton(MainPage)
        self.pbt6.setGeometry(QtCore.QRect(150, 120, 41, 31))
        self.pbt6.setObjectName("pbt6")
        self.pbt7 = QtWidgets.QPushButton(MainPage)
        self.pbt7.setGeometry(QtCore.QRect(40, 160, 41, 31))
        self.pbt7.setObjectName("pbt7")
        self.pbt8 = QtWidgets.QPushButton(MainPage)
        self.pbt8.setGeometry(QtCore.QRect(90, 160, 41, 31))
        self.pbt8.setObjectName("pbt8")
        self.pbt9 = QtWidgets.QPushButton(MainPage)
        self.pbt9.setGeometry(QtCore.QRect(150, 160, 41, 31))
        self.pbt9.setObjectName("pbt9")
        self.pbt0 = QtWidgets.QPushButton(MainPage)
        self.pbt0.setGeometry(QtCore.QRect(40, 200, 41, 31))
        self.pbt0.setObjectName("pbt0")
        self.btn_divide = QtWidgets.QPushButton(MainPage)
        self.btn_divide.setGeometry(QtCore.QRect(210, 120, 41, 31))
        self.btn_divide.setObjectName("btn_divide")
        self.btn_multiply = QtWidgets.QPushButton(MainPage)
        self.btn_multiply.setGeometry(QtCore.QRect(210, 80, 41, 31))
        self.btn_multiply.setObjectName("btn_multiply")
        self.btn_addition = QtWidgets.QPushButton(MainPage)
        self.btn_addition.setGeometry(QtCore.QRect(210, 160, 41, 31))
        self.btn_addition.setObjectName("btn_addition")
        self.btn_subtraction = QtWidgets.QPushButton(MainPage)
        self.btn_subtraction.setGeometry(QtCore.QRect(210, 200, 41, 31))
        self.btn_subtraction.setObjectName("btn_subtraction")
        self.btn_cal = QtWidgets.QPushButton(MainPage)
        self.btn_cal.setGeometry(QtCore.QRect(100, 250, 91, 31))
        self.btn_cal.setObjectName("btn_cal")
        self.lcdNumber = QtWidgets.QLCDNumber(MainPage)
        self.lcdNumber.setGeometry(QtCore.QRect(160, 22, 81, 31))
        self.lcdNumber.setObjectName("lcdNumber")

        self.retranslateUi(MainPage)
        QtCore.QMetaObject.connectSlotsByName(MainPage)

    def retranslateUi(self, MainPage):
        _translate = QtCore.QCoreApplication.translate
        MainPage.setWindowTitle(_translate("MainPage", "Form"))
        self.pbt1.setText(_translate("MainPage", "1"))
        self.pbt2.setText(_translate("MainPage", "2"))
        self.pbt3.setText(_translate("MainPage", "3"))
        self.pbt4.setText(_translate("MainPage", "4"))
        self.pbt5.setText(_translate("MainPage", "5"))
        self.pbt6.setText(_translate("MainPage", "6"))
        self.pbt7.setText(_translate("MainPage", "7"))
        self.pbt8.setText(_translate("MainPage", "8"))
        self.pbt9.setText(_translate("MainPage", "9"))
        self.pbt0.setText(_translate("MainPage", "0"))
        self.btn_divide.setText(_translate("MainPage", "/"))
        self.btn_multiply.setText(_translate("MainPage", "*"))
        self.btn_addition.setText(_translate("MainPage", "+"))
        self.btn_subtraction.setText(_translate("MainPage", "-"))
        self.btn_cal.setText(_translate("MainPage", "计算"))
